### ISSUE TITLE
Rename "genmd5" to "getMd5" or "getMD5"

### ISSUE THREAD

**Issue by cmp-ams** [light-bringer/wsse-headers#3]
https://github.com/light-bringer/wsse-headers/blob/b30a15d5812145f4197816c71d9370a1f2487920/wsse-headers/utilities.py#L52

**Comment by light-bringer** [comment]
fixed from #1  #2  https://github.com/light-bringer/wsse-headers/commit/8d84302f5ffd624edb3a5fd6ea2dd8e94a42300d
